import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Sidebar for the general docs plugin content. */
const sidebars: SidebarsConfig = {
    docs: [
        {
            id: "index",
            label: "🏠 Docs home",
            type: "doc",
        },
        {
            collapsed: true,
            items: [
                {
                    dirName: "developer/api",
                    type: "autogenerated",
                },
            ],
            label: "👨‍💻 Developer API",
            link: {
                id: "developer/api/index",
                type: "doc",
            },
            type: "category",
        },
    ],
};

export default sidebars;
